export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const INIT_INGREDIENT='INIT_INGREDIENT';
export const INIT_INGREDIENT_FAILED = 'INIT_INGREDIENT_FAILED';


export const PURCHASE_BURGER_STARTED='PURCHASE_BURGER_STARTED'
export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED='PURCHASE_BURGER_FAILED';
export const PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDERS_STARTED='FETCH_ORDERS_STARTED';
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED='FETCH_ORDERS_FAILED';

export const AUTH_START ='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAILED='AUTH_FAILED';
export const AUTH_LOGOUT ='AUTH_LOGOUT';

